# Generated by Django 3.1.1 on 2020-09-09 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('module_name', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'module',
            },
        ),
        migrations.CreateModel(
            name='Testcase',
            fields=[
                ('Test_Case_Id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Test_Case_Description', models.CharField(max_length=1000)),
                ('testcase_slug', models.CharField(max_length=20)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client', to='TestCase.client')),
            ],
        ),
        migrations.CreateModel(
            name='Testcasedetail',
            fields=[
                ('Test_Step_Id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Test_Step_Description', models.CharField(max_length=100)),
                ('Keyword', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('AP', 'Approved'), ('DA', 'Disapproved')], default='AP', max_length=10)),
                ('testcase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testcase', to='TestCase.testcase')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module', to='TestCase.module'),
        ),
    ]
