# Generated by Django 3.1.1 on 2020-09-14 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestCase', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcasedetail',
            name='status',
            field=models.CharField(choices=[('AP', 'Approved'), ('DA', 'Disapproved')], max_length=10, null=True),
        ),
    ]
